### ISSUE TITLE
Spelling mistakes in longdesc

### ISSUE THREAD

**Issue by robinwhittleton** [RiceKrisBs/sax-rohmer_brood-of-the-witch-queen#1]
- suspet
- Egypitan

**Comment by RiceKrisBs** [comment]
Corrected these typos. I've also updated the long description in general based on your feedback in the Google Group. Specifically, I shortened the plot summary to the second paragraph, so that the third paragraph gives a little context about Rohmer's frequent use of foreign settings and how the book is generally well received.
